{% set name = "asttrs" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asttrs-{{ version }}.tar.gz
  sha256: 39f3cd8bbecdeecff6c851d9cdb59e600a22611967cb2a0e1c5988d01a23233d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<3.11
    - attrs
    - black
    - cattrs
    - isort
    - ast-decompiler

test:
  imports:
    - asttrs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ryanchao2012/asttrs
  summary: A attrs-style wrapper for python ast
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
