{% set name = "asttrs" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asttrs-{{ version }}.tar.gz
  sha256: dbe74c79ecc6d57515ba5f776371bc44bd9c3937cadd850a3f3c1b059e08df6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - poetry
  run:
    - python >=3.7,<3.11
    - attrs
    - black
    - cattrs
    - isort
    - ast-decompiler

test:
  imports:
    - asttrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ryanchao2012/asttrs
  summary: A attrs-style wrapper for python ast
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
