# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: asttrs
  version: "1.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/asttrs-${{ version }}.tar.gz
  sha256: 39f3cd8bbecdeecff6c851d9cdb59e600a22611967cb2a0e1c5988d01a23233d

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }},<3.11
    - attrs
    - black
    - cattrs
    - isort
    - ast-decompiler

tests:
  - python:
      imports:
        - asttrs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A attrs-style wrapper for python ast
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ryanchao2012/asttrs

extra:
  recipe-maintainers:
    - rxm7706
